### ISSUE TITLE
Separate out methods into a modules file

### ISSUE THREAD

**Issue by samleemcknight** [RamonJOrtega/jobSearchApp#1]
In your controller you have a few methods (like [this one](https://github.com/ramon6767/jobSearchApp/blob/main/index.js#L34)) that you can move into a separate file and import it in. I'm thinking something like this (it would be in its own file)

```javascript
const companyFrequency = (jobArray) => {
    let counter = {};
    for (element of jobArray) {
        if (counter[element]) {
            counter[element] += 1;
        } else {
            counter[element] = 1;
        }
    };
    const freqArray = Object.entries(counter);
    sortedFreqArray = freqArray.sort((a,b) => b[1]-a[1]);
    return sortedFreqArray;
}
export default companyFrequency;
```

**Comment by RamonJOrtega** [comment]
Agree! Is there a way to protect certain functions or variables from html
inspectors?

Ramon

**Comment by samleemcknight** [comment]
Not sure I follow - do you mean hiding it from being exposed in a browser inspector? Moving utility/helper functions like the one above can help with that

**Comment by samleemcknight** [comment]
btw, if you're interested, here is an example of how you can lay out an express project. It was one of the projects I did in my boot camp, based off of one of the templates they shared with us:
https://github.com/samleemcknight/cocktail_codex
