### ISSUE TITLE
Fix Navbar, be creative, make it pretty

### ISSUE THREAD

**Issue by RamonJOrtega** [RamonJOrtega/jobSearchApp#4]
Navbar currently crashes app when navigating to pages other than home.
Fix the crashing issues.

Additionally, navbar lists all unique companies (represented by number) which results in too many (100s) of navbar elements. Replace elements with something cleaner. Example: add a search box.

**Comment by samleemcknight** [comment]
You should separate your concerns here and make your own javascript file in the `public` directory (I'd suggest something like `public/javascript` and loading it in like this:
https://www.w3schools.com/tags/att_script_src.asp
